// neutron-im-web/src/pages/Login/index.tsx
import React, { useCallback, useEffect } from 'react';

import { message } from 'antd';
import { postAccount, postAccountLogin } from '@/services/user';
import { isEmail, isPassword } from '@/utils/validate';
import { setUserInfo, setHasLogin } from '@/store/userInfoSlice';

import styles from './Login.module.less';
import { withRouter } from 'react-router-dom';
import { useAppDispatch } from '@/store';
import { createSemaphore } from '@/utils/wrapper';
import LoginForm from './LoginForm';
import RegisterForm from './RegisterForm';
import { exportUserInfo } from '@/utils/localStorage';
import { Helmet } from 'react-helmet-async';
import { FormattedMessage, useIntl } from 'react-intl';

import type { RegisterParams } from './RegisterForm';
import type { LoginParams } from './LoginForm';
import type { UserInfoSubstate } from '@/types/state';
import { useGetParams } from '@/utils/hooks';
import { useSafeState } from 'ahooks';
import type { NimSafeAny } from '@/types';

const MESSAGE_KEY = 'MESSAGE_KEY';
const loginStatus = createSemaphore();
const logonStatus = createSemaphore();

export default withRouter(function Login(props) {
  const dispatch = useAppDispatch();
  const [isLogin, setIsLogin] = useSafeState(true);
  const urlParams = useGetParams({
    redirect: '',
    tab: 'login',
  });

  const intl = useIntl();

  useEffect(() => {
    if (urlParams.tab && urlParams.tab === 'logon') {
      setIsLogin(false);
    } else {
      setIsLogin(true);
    }
  });

  // 处理提交
  const onSubmit = useCallback(
    async ({ email, password, captcha }: LoginParams) => {
      if (loginStatus.loading === 'pending') return;

      // 检查验证码的合理性
      if (!isEmail(email) || !isPassword(password) || !captcha) {
        message.destroy(MESSAGE_KEY);
        message.error(
          intl.formatMessage({
            id: 'app.login.form.invalid_account_password_format',
            defaultMessage: 'Invalid format of account or password',
          }),
          0.5,
        );
        return;
      }

      message.loading({
        content: intl.formatMessage({
          id: 'app.login.logging',
          defaultMessage: 'Logging in...',
        }),
        key: MESSAGE_KEY,
      });
      loginStatus.loading = 'pending';
      const res = await postAccountLogin({
        email,
        password,
        captcha,
      });
      loginStatus.loading = 'idle';
      message.destroy(MESSAGE_KEY);

      if (res.status !== 20000 || !res.data || typeof res.data !== 'object') {
        message.error(res.message);
        console.log(res);
        return;
      }

      message.info(
        intl.formatMessage({
          id: 'app.login.logged',
          defaultMessage: 'Logged in',
        }),
        0.3,
      );

      // 获取用户信息，并初始化 redux 中的 userInfo
      // 更新用户的登录状态
      dispatch(setHasLogin(true));
      dispatch(setUserInfo(res.data as UserInfoSubstate));
      exportUserInfo(res.data as Record<string, NimSafeAny>);

      setTimeout(() => {
        // 跳转页面
        if (urlParams.redirect && typeof urlParams.redirect === 'string') {
          props.history.push(decodeURI(urlParams.redirect));
        } else {
          props.history.push('/im');
        }
      }, 500);
    },
    [dispatch, urlParams, props.history, intl],
  );

  const submitReg = useCallback(
    async (params: RegisterParams) => {
      if (logonStatus.loading === 'pending') return;

      // 检查验证码的合理性
      if (
        !isEmail(params.email) ||
        !isPassword(params.password) ||
        !params.nickname ||
        !params.captcha
      ) {
        message.destroy(MESSAGE_KEY);
        message.error(
          intl.formatMessage({
            id: 'app.login.form.invalid_account_password_format',
            defaultMessage: 'Invalid format of account or password',
          }),
          0.5,
        );
        return;
      }

      // const MESSAGE_KEY = "MESSAGE_KEY";
      message.loading({
        content: '注册中...',
        key: MESSAGE_KEY,
      });
      logonStatus.loading = 'pending';
      const res = await postAccount({
        email: params.email,
        password: params.password,
        nickname: params.nickname,
        captcha: params.captcha,
      });
      logonStatus.loading = 'idle';
      message.destroy(MESSAGE_KEY);

      // 验证登录结果，需要重新实现验证效果
      if (!res || res.status !== 20000) {
        message.error(`注册失败，${res.message}`);
        return;
      }

      message.info(
        intl.formatMessage({
          id: 'app.register.registered',
          defaultMessage: 'Register successfully',
        }),
        0.2,
      );
    },
    [intl],
  );

  return (
    <div
      className={styles.fullscreenContainer}
      style={{ backgroundImage: 'url(/assets/login-bg.jpg)' }}
    >
      <Helmet>
        <title>
          {intl.formatMessage({
            id: 'app.login',
            defaultMessage: 'Sign in to Neutron-IM',
          })}
        </title>
      </Helmet>
      <div className={styles.formContainer}>
        <div
          style={{ backgroundImage: 'url(/assets/login-bg.jpg)' }}
          className={styles.imgDesc}
        >
          <div className={styles.brandDescBox}>
            <div className={styles.brandDesc}>Made for Developers</div>
            <div className={styles.brandDesc}>
              {' '}
              更
              <span
                style={{
                  color: 'rgba(64, 169, 255, 0.65)',
                }}
              >
                「 IT 」
              </span>
              的即时通讯工具
            </div>
            <div className={styles.brandName}>Neutron IM</div>
          </div>
        </div>
        <div className={styles.form}>
          <div className={styles.title}>
            <span
              style={{
                fontSize: '14px',
                lineHeight: '22px',
                color: 'rgba(0, 0, 0, 0.45)',
                fontWeight: 500,
              }}
            >
              <FormattedMessage
                id="app.login.greeting"
                description="Greeting to welcome the user to the app"
                defaultMessage="Hello, {name}!"
                values={{
                  name: 'Eric',
                }}
              />
            </span>
            <br />
            Neutron IM
          </div>
          {isLogin ? (
            <LoginForm onSubmit={onSubmit} />
          ) : (
            <RegisterForm onSubmit={submitReg} />
          )}
          <div>
            <div style={{ color: 'rgba(0,0,0,0.45)' }}>Or</div>
            <div>
              <span
                style={{
                  textDecoration: 'underline',
                  cursor: 'pointer',
                  color: 'rgba(0,0,0,0.65)',
                }}
                onClick={() => {
                  const searchStr = new URLSearchParams({
                    ...urlParams,
                    tab: isLogin ? 'logon' : 'login',
                  }).toString();
                  setIsLogin(!isLogin);
                  props.history.replace({
                    pathname: props.location.pathname,
                    search: searchStr ? `?${searchStr}` : '',
                  });
                }}
              >
                {isLogin ? (
                  <FormattedMessage
                    id="app.register"
                    defaultMessage="Register"
                  />
                ) : (
                  <FormattedMessage id="app.login" defaultMessage="Login" />
                )}
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
});

// neutron-im-web/src/app/login/login/login.component.ts
import { I18nService } from '@/components/i18n';
import { RegisterParams, UserRestService } from '@/services/user-rest.service';
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { NzMessageService } from 'ng-zorro-antd/message';

@Component({
  selector: 'nim-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.less']
})
export class LoginComponent {
  validateForm!: FormGroup;

  isLogin = true;

  isSubmitting = false;

  constructor(
    private message: NzMessageService,
    private i18n: I18nService,
    private userRest: UserRestService,
    private fb: FormBuilder
  ) {
    this.validateForm = this.fb.group({
      email: ['', [Validators.email]],
      password: [null, [Validators.required]],
      captcha: ['', (val: any) => {
        // console.log(val)
        return {
          result: true,
        }
      }],

      // 以下内容仅注册时需要填写
      // name: [null, [Validators.required]],
      // repassword: [null, [Validators.required]],

    });
  }

  get formValue() {
    return this.validateForm.value as RegisterParams;
  }

  login() {
    if (this.isSubmitting) {
      return;
    }
    this.isSubmitting = true;

    console.log(this.formValue);
    this.validateForm.updateValueAndValidity();
    if (this.validateForm.invalid) {
      console.log('错误提示：表单有错');
      this.isSubmitting = false;
      return;
    }

    this.isSubmitting = false;
    // this.validateForm.
    // const { email, password, captcha } = this.validateForm;
    // // 检查验证码的合理性
    // if (!isEmail(email) || !isPassword(password) || !captcha) {
    //   // this.message.destroy(MESSAGE_KEY);
    //   this.message.error(
    //     this.i18n.get(
    //       'app.login.form.invalid_account_password_format'
    //     ),
    //    { nzDuration:  0.5}
    //   );
    //   return;
    // }

    // this.submitting = true;
    // this.message.loading(this.i18n.get('app.login.logging'));

    // this.userRest.postAccountLogin({ email, password, captcha }).subscribe(val => {
    //   console.log(val)
    // });
  }

  switchLoginOrReg() {
    this.isLogin = !this.isLogin;
    // const searchStr = new URLSearchParams({
    //   ...urlParams,
    //   tab: isLogin ? 'logon' : 'login',
    // }).toString();
    // setIsLogin(!isLogin);
    // props.history.replace({
    //   pathname: props.location.pathname,
    //   search: searchStr ? `?${searchStr}` : '',
    // });
  }


}



// rules = {
//   email: [{
//     required: true,
//     pattern:
//       /^[A-Za-z0-9]+([.+-_][a-zA-Z0-9]+)*@[A-Za-z0-9]+([.-][a-zA-Z0-9]+)*\.[A-Za-z]{2,14}$/,
//     message: 'Please input your email correctly!',
//   }],
//   password: [{
//     required: true,
//     pattern: /^\w{6,16}$/,
//     message: 'Please input your password correctly!',
//   }]
// }

// formData = {
//   email: '',
//   name: '',
//   password: '',
//   repassword: '',
//   captcha: ''
// };

<div class="fullscreenContainer" style="background-image: 'url(/assets/login-bg.jpg)'">
  <div class="formContainer">
    <div style="background-image: 'url(/assets/login-bg.jpg)' " class="imgDesc">
      <div class="brandDescBox">
        <div class="brandDesc">Made for Developers</div>
        <div class="brandDesc">
          更<span style="color: 'rgba(64, 169, 255, 0.65)'">「 IT 」</span>的即时通讯工具
        </div>
        <div class="brandName">Neutron IM</div>
      </div>
    </div>
    <div class="form">
      <div class="title">
        <span style="font-Size: '14px'; line-Height: '22px';color: 'rgba(0, 0, 0, 0.45)'; font-Weight: 500">
          {{ 'app.login.greeting' | i18n:'Eric' }}
        </span>
        <br />
        Neutron IM
      </div>
      <form nz-form class="loginForm" [formGroup]="validateForm" (ngSubmit)="login()">
        <nz-form-item>
          <nz-input-group nzPrefixIcon="mail">
            <input nz-input type="email" formControlName="email" placeholder="{{ 'app.login.email' }}" />
          </nz-input-group>
        </nz-form-item>

        <nz-form-item *ngIf="!isLogin">
          <nz-input-group nzPrefixIcon="idcard">
            <input nz-input type="text" formControlName="name" placeholder="{{ 'app.login.username' }}" />
          </nz-input-group>
        </nz-form-item>

        <nz-form-item>
          <nz-input-group nzPrefixIcon="lock">
            <input nz-input type="password" formControlName="password" placeholder="{{ 'app.login.password' }}" />
          </nz-input-group>
        </nz-form-item>

        <nz-form-item *ngIf="!isLogin">
          <nz-input-group nzPrefixIcon="lock">
            <input nz-input type="password" formControlName="repassword" placeholder="{{ 'app.login.repassword' }}" />
          </nz-input-group>
        </nz-form-item>

        <nz-form-item [nzGutter]="8">
          <nz-col nzSpan="16">
            <nz-input-group>
              <input nz-input formControlName="captcha" placeholder="{{ 'app.login.captcha' }}" />
            </nz-input-group>
          </nz-col>
          <nz-col nzSpan="8">
            <nim-captcha></nim-captcha>
          </nz-col>
        </nz-form-item>

        <nz-form-item nzAlign="bottom" nzGutter="16">
          <nz-col>
            <button nz-button nzType="primary" [nzLoading]="isSubmitting">
              <i nz-icon nzType="login" nzTheme="outline"></i><span>{{ 'app.login.submit' | i18n }}</span>
            </button>
          </nz-col>

          <nz-col>
            <span class="text-switch-or">Or</span>
            <span class="text-switch-mode" (click)="switchLoginOrReg()">
              {{isLogin ? ('app.register' | i18n) : ('app.login' | i18n)}}
            </span>
          </nz-col>
        </nz-form-item>
      </form>

    </div>
  </div>
</div>
