// src/pages/Account/Login/Captcha.tsx
import React, { useState } from "react";
import { generateCaptcha } from "@/utils/generator";

const getCaptchaUrl = () => {
  return `${process.env.REACT_APP_API_BASE_URL || '//localhost:3001'}/captcha-pic?id=${generateCaptcha()}`
}

export default function Captcha(props:any) {

  const [captchaUrl, setCaptchaUrl] = useState(getCaptchaUrl);
  
  const reloadCaptcha = () => {
    setCaptchaUrl(getCaptchaUrl())
  }

  return <img src={captchaUrl} alt="captcha" onClick={reloadCaptcha} {...props}/>
}

// neutron-im-web/src/app/login/captcha/captcha.component.ts
import { HTTP_BASE_URL_TOKEN } from '@/components/http/http.token';
import { generateCaptcha } from '@/utils/generator';
import { Component, Inject } from '@angular/core';

@Component({
  selector: 'nim-captcha',
  templateUrl: './captcha.component.html',
  styleUrls: ['./captcha.component.less']
})
export class CaptchaComponent {
  captchaUrl = ''

  constructor(@Inject(HTTP_BASE_URL_TOKEN) private baseUrl: string) {
    this.setCaptchaUrl()
  }

  setCaptchaUrl() {
    this.captchaUrl = `${(this.baseUrl ? this.baseUrl : '')}/captcha-pic?id=${generateCaptcha()}`
  }

  reloadCaptcha() {
    this.setCaptchaUrl();
  }
}

<img
  (click)="reloadCaptcha()"
  [src]="captchaUrl"
  alt="{{ ('alt.captcha' | i18n )}}"
  class="captchaPic"
/>
